export const notes = [
	{
		slug: "architecting-a-scalable-image-upload-system",
		title: "Architecting a scalable image upload system",
		description: "Designing a robust image upload solution",
		date: "2026-06-23",
		tags: ["React", "Next.js", "Image Processing"],
		category: "Next.js",
		featured: true,
	},
	{
		slug: "building-a-reliable-PWA-with-Vite+React+TypeScript",
		title: "Building a reliable PWA with Vite, React, and TypeScript",
		description: "Creating a performant progressive web app",
		date: "2026-06-18",
		tags: ["React", "TypeScript", "PWA"],
		category: "React",
	},
	{
		slug: "fixing-module-not-found-(case-sensitivity)-issue",
		title: "Fixing module not found (Case Sensitivity) Issue",
		description: "Troubleshooting a common module resolution problem",
		date: "2026-06-18",
		tags: ["React", "Next.js", "Troubleshooting"],
		category: "Other",
	},
	{
		slug: "how-I-fixed-blank-screen-for-my-React-app-deployed-on-GitHub-pages",
		title:
			"How I fixed the blank screen for my React App deployed on GitHub Pages",
		description: "Troubleshooting a common deployment issue with React apps",
		date: "2026-06-17",
		tags: ["React", "Deployment", "Troubleshooting"],
		category: "Other",
	},
	{
		slug: "fixing-netlify-build-failures-after-migrating-from-Vite-to-Nextjs",
		title: "Fixing Netlify build failures after migrating from Vite to Next.js",
		description: "Troubleshooting deployment issues when migrating to Next.js",
		date: "2026-06-18",
		tags: ["Next.js", "Deployment", "Troubleshooting"],
		category: "Other",
	},
	{
		slug: "how-I-fixed-running-scripts-is-disabled-on-this-system-error",
		title: "How I fixed the 'Running scripts is disabled on this system' error",
		description: "Troubleshooting a common Windows PowerShell issue",
		date: "2026-05-16",
		tags: ["React", "Next.js", "Troubleshooting"],
		category: "Other",
	},
	{
		slug: "how-I-resolved-ENOENT-no-such-file-or-directory",
		title: "How I resolved the 'ENOENT: no such file or directory' Error",
		description: "Troubleshooting a common file system issue",
		date: "2026-06-17",
		tags: ["React", "Next.js", "Troubleshooting"],
		category: "Other",
	},
	{
		slug: "using-alias-imports-in-Nextjs",
		title: "Using alias imports in Next.js",
		description: "Learn how to use alias imports to simplify your code",
		date: "2026-06-17",
		tags: ["React", "Next.js", "Troubleshooting"],
		category: "Other",
	},
	{
		slug: "tracking-link-click-using-GTM-and Google-Analytics",
		title: "Tracking specific link clicks using GTM and Google Analytics",
		description:
			"Learn how to track link clicks with Google Tag Manager and Google Analytics",
		date: "2026-07-03",
		tags: ["Google Analytics", "Google Tag Manager"],
		category: "Other",
	},
];
